import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./tasarim/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bfc7d8",
        "on-secondary-container": "#00311f",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2b",
        "on-primary-fixed-variant": "#3f4755",
        "on-surface": "#e4e2e3",
        primary: "#bfc7d8",
        "on-background": "#e4e2e3",
        "tertiary-container": "#021225",
        "surface-container": "#1f1f20",
        tertiary: "#b7c8e1",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#005236",
        "inverse-primary": "#575f6d",
        "on-surface-variant": "#c5c6cc",
        "inverse-surface": "#e4e2e3",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-highest": "#353536",
        "surface-tint": "#bfc7d8",
        "on-tertiary-container": "#6e7e96",
        "primary-container": "#0a121e",
        "surface-variant": "#353536",
        surface: "#131314",
        "on-secondary": "#003824",
        "on-tertiary-fixed": "#0b1c30",
        "on-primary": "#29313e",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-low": "#1b1b1c",
        "inverse-on-surface": "#303031",
        "primary-fixed": "#dbe3f4",
        outline: "#8f9096",
        "surface-dim": "#131314",
        "on-secondary-fixed": "#002113",
        "surface-bright": "#39393a",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-fixed": "#141c28",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#213145",
        "on-error": "#690005",
        background: "#131314",
        secondary: "#4edea3",
        "on-primary-container": "#767d8d",
        "secondary-container": "#00a572",
        "outline-variant": "#45474c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "container-max": "1440px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "title-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "body-lg": ["Inter"],
        "display-lg": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
