-- supabase/migrations/20260517000002_create_admin_audit_log.sql

-- Admin Audit Log Table
create table public.admin_audit_logs (
    id bigint generated by default as identity primary key,
    admin_id text references public.users(id) not null,
    action text not null,
    target_type text,
    target_id text,
    details jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes
create index ix_admin_audit_logs_admin_id on public.admin_audit_logs (admin_id);
create index ix_admin_audit_logs_target_type_target_id on public.admin_audit_logs (target_type, target_id);

-- Enable RLS
alter table public.admin_audit_logs enable row level security;

-- Policies
create policy "Admins can view all audit logs" on public.admin_audit_logs for select using (auth.uid()::text in (select id from public.users where role = 'admin'));
